// Arabic copy for the homepage. Each pair is [English as it appears in src/home.html, Arabic].
// tools/build.js fails if an English string is not found, so a copy edit in src/home.html
// must be mirrored here. Plain "Arabic and English" wording only, no dialect claims.
module.exports = [
  // hero
  ['<span class="h1-kick">Arabic and English customer support outsourcing</span>', '<span class="h1-kick">تعهيد خدمة العملاء بالعربية والإنجليزية</span>'],
  ['<span class="ln">Your operations.</span> <span class="ln">Our people.</span> <span class="ln"><em>One standard.</em></span>',
   '<span class="ln">عملياتكم.</span> <span class="ln">فريقنا.</span> <span class="ln"><em>معيار واحد.</em></span>'],
  ['Native Arabic speakers with fluent English who answer your customers, process your cases and report to you every week. They work your hours, inside your own tools.',
   'فريق من المتحدثين الأصليين بالعربية يجيد الإنجليزية، يرد على عملائكم وينجز معاملاتكم ويرفع لكم تقريرًا كل أسبوع. يعمل في ساعات عملكم، وداخل أدواتكم أنتم.'],
  ['>Book a discovery call <', '>احجزوا مكالمة تعارف <'],
  ['>See what we run <', '>تعرّفوا على خدماتنا <'],
  ['<li><b>AR + EN</b><span>Both languages on every shift</span></li>', '<li><b>عربي + إنجليزي</b><span>اللغتان في كل وردية</span></li>'],
  ['<li><b>Your tools</b><span>Your systems, your data</span></li>', '<li><b>أدواتكم</b><span>أنظمتكم وبياناتكم تبقى لكم</span></li>'],
  ['<li><b>Weekly</b><span>A report on your account</span></li>', '<li><b>أسبوعيًا</b><span>تقرير عن حسابكم</span></li>'],
  ['aria-label="Illustration of a Zameel support agent wearing a headset"', 'aria-label="رسم لموظف دعم من زميل يرتدي سماعة رأس"'],
  ['<div class="bubble c" style="transition-delay:.7s">Customers waiting on a reply?<small>10:02</small></div>',
   '<div class="bubble c" style="transition-delay:.7s">عملاؤكم ينتظرون الرد؟<small>10:02</small></div>'],
  ['<div class="bubble a" style="transition-delay:1.1s">Not anymore. Answered in Arabic and English, in your hours.<small>10:02 ✓✓</small></div>',
   '<div class="bubble a" style="transition-delay:1.1s">ليس بعد اليوم. نرد بالعربية والإنجليزية، في ساعات عملكم.<small>10:02 ✓✓</small></div>'],

  // channels
  ['Everything your customers see, <em>and the paperwork behind it.</em>', 'كل ما يراه عملاؤكم، <em>وكل المعاملات خلف الكواليس.</em>'],
  ['<h3>Messaging<br>support</h3><p>WhatsApp, Instagram and live chat, answered in the customer\'s language.</p>', '<h3>دعم<br>المحادثات</h3><p>واتساب وإنستغرام والمحادثة المباشرة، بلغة العميل نفسها.</p>'],
  ['<h3>Email and<br>tickets</h3><p>Queues worked inside your helpdesk, with your macros and tone.</p>', '<h3>البريد<br>والتذاكر</h3><p>نعمل على طوابير التذاكر داخل نظامكم، بردودكم الجاهزة وأسلوبكم.</p>'],
  ['<h3>Voice<br>support</h3><p>Inbound and outbound calls in Arabic and English.</p>', '<h3>دعم<br>المكالمات</h3><p>مكالمات واردة وصادرة بالعربية والإنجليزية.</p>'],
  ['<h3>Back-office</h3><p>Document processing, data entry and case admin, done to your checklists.</p>', '<h3>الأعمال المكتبية</h3><p>معالجة المستندات وإدخال البيانات وإدارة الحالات، وفق قوائمكم.</p>'],
  ['<h3>Underwriting<br>and KYC</h3><p>Identity checks, claims and policy admin for regulated teams.</p>', '<h3>الاكتتاب<br>والتحقق</h3><p>التحقق من الهوية والمطالبات وإدارة الوثائق للجهات المنظَّمة.</p>'],
  ['<h3>Quality and<br>reporting</h3><p>Scorecards, coaching and a weekly report on every account.</p>', '<h3>الجودة<br>والتقارير</h3><p>بطاقات تقييم وتدريب مستمر وتقرير أسبوعي لكل حساب.</p>'],

  // team / phone
  ['Real people, working as part of <em>your team.</em>', 'أشخاص حقيقيون، يعملون <em>كجزء من فريقكم.</em>'],
  ['Customers write in Arabic, switch to English halfway through, and expect a reply in minutes. Our agents answer in the language the customer used, in your tone, with your saved replies and your escalation rules.',
   'يكتب العميل بالعربية، ثم ينتقل إلى الإنجليزية في منتصف المحادثة، وينتظر الرد خلال دقائق. يرد فريقنا باللغة التي استخدمها العميل، بأسلوبكم وردودكم الجاهزة وقواعد التصعيد لديكم.'],
  ['<li>Native Arabic speakers with fluent English</li>', '<li>متحدثون أصليون بالعربية يجيدون الإنجليزية</li>'],
  ['<li>First reply on chat in under 2 minutes</li>', '<li>أول رد على المحادثة خلال أقل من دقيقتين</li>'],
  ['<li>Works in Zendesk, Freshdesk, Intercom or your own CRM</li>', '<li>نعمل على Zendesk أو Freshdesk أو Intercom أو نظامكم الخاص</li>'],
  ['<li>Nothing is machine translated</li>', '<li>لا شيء مترجم آليًا</li>'],
  ['aria-label="Example support chat. Pick a question to see how an agent replies."', 'aria-label="محادثة دعم تجريبية. اختاروا سؤالًا لتروا كيف يرد الموظف."'],
  ['<b class="hn">Your brand</b><span><i></i>Online · answered by Zameel</span>', '<b class="hn">علامتكم</b><span><i></i>متصل · يرد عليه فريق زميل</span>'],
  [`              <div class="bub c">Hi, my order hasn't arrived yet.<small>10:02</small></div>
              <div class="bub a">Sorry about that! It's out for delivery today. Tracking link sent.<small>10:03 ✓✓</small></div>
              <div class="bub c ar" lang="ar">شكراً، هل يمكنني تغيير العنوان؟<small>10:04</small></div>
              <div class="bub a ar" lang="ar">بالتأكيد، تم تحديث العنوان.<small>10:04 ✓✓</small></div>`,
   `              <div class="bub c">مرحبًا، طلبي لم يصل بعد.<small>10:02</small></div>
              <div class="bub a">نعتذر عن ذلك! طلبكم خرج للتوصيل اليوم، وأرسلنا رابط التتبع.<small>10:03 ✓✓</small></div>
              <div class="bub c en" lang="en" dir="ltr">Thanks, can I change the address?<small>10:04</small></div>
              <div class="bub a en" lang="en" dir="ltr">Of course, the address is updated.<small>10:04 ✓✓</small></div>`],
  [`              <div class="bub c">Hi, my order hasn't arrived yet.</div>
              <div class="bub a">Sorry about that! It's out for delivery today. Tracking link sent.</div>
              <div class="bub c ar">شكراً، هل يمكنني تغيير العنوان؟</div>
              <div class="bub a ar">بالتأكيد، تم تحديث العنوان.</div>`,
   `              <div class="bub c">مرحبًا، طلبي لم يصل بعد.</div>
              <div class="bub a">نعتذر عن ذلك! طلبكم خرج للتوصيل اليوم، وأرسلنا رابط التتبع.</div>
              <div class="bub c en">Thanks, can I change the address?</div>
              <div class="bub a en">Of course, the address is updated.</div>`],
  ['<p>Ask as a customer</p>', '<p>اسألوا كعميل</p>'],
  ['<button type="button" data-q="refund">Refund on a damaged item</button>', '<button type="button" data-q="refund">استرجاع منتج تالف</button>'],
  ['<button type="button" data-q="invoice" lang="ar">أحتاج فاتورة</button>', '<button type="button" data-q="invoice" lang="en" dir="ltr">I need an invoice</button>'],
  ['<button type="button" data-q="hours">Open this evening?</button>', '<button type="button" data-q="hours">متاحون هذا المساء؟</button>'],

  // handled grid
  ['Support, back-office and quality, <em>handled.</em>', 'الدعم والأعمال المكتبية والجودة، <em>في أيدٍ أمينة.</em>'],
  ['A week on your account, in four cards. Your queues get cleared, cases get checked, conversations get scored, and your account manager sends you the numbers.',
   'أسبوع على حسابكم في أربع بطاقات. تُنجز الطوابير، وتُراجع الحالات، وتُقيَّم المحادثات، ويرسل لكم مدير حسابكم الأرقام.'],
  ['<div class="kicker">Messaging &amp; email</div><h3>Inbox</h3>', '<div class="kicker">المحادثات والبريد</div><h3>صندوق الوارد</h3>'],
  ['<div class="count done" id="cnt">All caught up ✓</div>', '<div class="count done" id="cnt">لا شيء معلّق ✓</div>'],
  ['<span class="t">Order status</span><span class="via">· WhatsApp</span><button type="button" class="pill" aria-label="Toggle resolved: order status">Open<span class="done">✓ Resolved</span></button>',
   '<span class="t">حالة الطلب</span><span class="via">· واتساب</span><button type="button" class="pill" aria-label="تبديل الحالة: حالة الطلب">مفتوحة<span class="done">✓ تم الحل</span></button>'],
  ['<span class="t">Refund request</span><span class="via">· Email</span><button type="button" class="pill" aria-label="Toggle resolved: refund request">Open<span class="done">✓ Resolved</span></button>',
   '<span class="t">طلب استرجاع</span><span class="via">· البريد</span><button type="button" class="pill" aria-label="تبديل الحالة: طلب استرجاع">مفتوحة<span class="done">✓ تم الحل</span></button>'],
  ['<span class="t ar" lang="ar">تحديث الحساب</span><span class="via">· Live chat</span><button type="button" class="pill" aria-label="Toggle resolved: account update">Open<span class="done">✓ Resolved</span></button>',
   '<span class="t en" lang="en">Account update</span><span class="via">· المحادثة المباشرة</span><button type="button" class="pill" aria-label="تبديل الحالة: تحديث الحساب">مفتوحة<span class="done">✓ تم الحل</span></button>'],
  ['aria-label="Your account manager"', 'aria-label="مدير حسابكم"'],
  ['<div class="kicker">Account manager</div><h3>One named contact</h3><p class="sub">Weekly report on volumes and quality</p>',
   '<div class="kicker">مدير الحساب</div><h3>جهة تواصل واحدة</h3><p class="sub">تقرير أسبوعي عن الأحجام والجودة</p>'],
  ['<span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span class="sent" id="sent">Report sent ✓</span>',
   '<span>الأحد</span><span>الاثنين</span><span>الثلاثاء</span><span>الأربعاء</span><span>الخميس</span><span class="sent" id="sent">أُرسل التقرير ✓</span>'],
  ['<div class="kicker">Back-office &amp; KYC</div><h3>Customer onboarding</h3>', '<div class="kicker">الأعمال المكتبية والتحقق</div><h3>تسجيل عميل جديد</h3>'],
  ['</span></span>ID document checked</div>', '</span></span>فُحصت وثيقة الهوية</div>'],
  ['</span></span>Address verified</div>', '</span></span>تم التحقق من العنوان</div>'],
  ['</span></span>Screening complete</div>', '</span></span>اكتمل الفحص</div>'],
  ['</span></span>Data entered</div>', '</span></span>أُدخلت البيانات</div>'],
  ['<div class="appr" id="appr">File ready for approval</div>', '<div class="appr" id="appr">الملف جاهز للاعتماد</div>'],
  ['<div class="kicker">Quality</div><h3>One standard.</h3>', '<div class="kicker">الجودة</div><h3>معيار واحد.</h3>'],
  ['<p class="sub">Conversations reviewed against your scorecard.</p>', '<p class="sub">تُراجع المحادثات وفق بطاقة التقييم لديكم.</p>'],
  ['<span class="chip">Accuracy<span class="f">✓ Accuracy</span></span>', '<span class="chip">الدقة<span class="f">✓ الدقة</span></span>'],
  ['<span class="chip">Tone<span class="f">✓ Tone</span></span>', '<span class="chip">الأسلوب<span class="f">✓ الأسلوب</span></span>'],
  ['<span class="chip">Resolution<span class="f">✓ Resolution</span></span>', '<span class="chip">الحل<span class="f">✓ الحل</span></span>'],
  ['<span class="chip">Compliance<span class="f">✓ Compliance</span></span>', '<span class="chip">الالتزام<span class="f">✓ الالتزام</span></span>'],
  ['</svg>Run the week again</button>', '</svg>أعيدوا تشغيل الأسبوع</button>'],

  // service tabs
  ['<h2 class="h2">What we take off your team\'s plate.</h2>', '<h2 class="h2">ما نرفعه عن كاهل فريقكم.</h2>'],
  ['aria-label="Services" id="tabs"', 'aria-label="الخدمات" id="tabs"'],
  ['aria-selected="true">Customer care</button>', 'aria-selected="true">خدمة العملاء</button>'],
  ['tabindex="-1">Back-office and underwriting</button>', 'tabindex="-1">الأعمال المكتبية والاكتتاب</button>'],
  ['tabindex="-1">Peak-season cover</button>', 'tabindex="-1">تغطية المواسم</button>'],
  ['<h3>Every message answered in the language your customer used.</h3>', '<h3>كل رسالة يُرد عليها باللغة التي كتب بها عميلكم.</h3>'],
  ['<p>Your tone, your saved replies, your escalation rules. Refunds, order tracking, complaints and pre-sale questions, handled by people who know your products.</p>',
   '<p>بأسلوبكم وردودكم الجاهزة وقواعد التصعيد لديكم. الاسترجاع وتتبع الطلبات والشكاوى وأسئلة ما قبل الشراء، على يد فريق يعرف منتجاتكم.</p>'],
  ['<span class="tag">WhatsApp</span><span class="tag">Instagram</span><span class="tag">Live chat</span><span class="tag">Email</span><span class="tag">Voice</span>',
   '<span class="tag">واتساب</span><span class="tag">إنستغرام</span><span class="tag">محادثة مباشرة</span><span class="tag">بريد إلكتروني</span><span class="tag">مكالمات</span>'],
  ['More on customer support outsourcing <svg', 'المزيد عن تعهيد خدمة العملاء <svg'],
  ['<li>Weekly report on volumes, response times and issues</li>', '<li>تقرير أسبوعي عن الأحجام وأوقات الرد والمشكلات</li>'],
  ['<h3>Careful, checklist-driven work for regulated teams.</h3>', '<h3>عمل دقيق وفق قوائم تحقق، للجهات المنظَّمة.</h3>'],
  ['<p>Document processing, KYC checks, claims and policy admin, merchant onboarding. Each case done to your checklist and logged in your system.</p>',
   '<p>معالجة المستندات والتحقق من هوية العملاء وإدارة المطالبات والوثائق وتسجيل التجار. كل حالة وفق قائمتكم ومسجلة في نظامكم.</p>'],
  ['<span class="tag">KYC</span><span class="tag">Claims</span><span class="tag">Policy admin</span><span class="tag">Merchant onboarding</span>',
   '<span class="tag">اعرف عميلك</span><span class="tag">المطالبات</span><span class="tag">إدارة الوثائق</span><span class="tag">تسجيل التجار</span>'],
  ['More on back-office and KYC <svg', 'المزيد عن الأعمال المكتبية والتحقق <svg'],
  ['<li>Every case logged and traceable in your system</li>', '<li>كل حالة مسجلة ويمكن تتبعها في نظامكم</li>'],
  ['<li>Agents work only inside your accounts</li>', '<li>يعمل فريقنا داخل حساباتكم فقط</li>'],
  ['<li>Data processing agreement signed before go-live</li>', '<li>اتفاقية معالجة بيانات تُوقَّع قبل بدء العمل</li>'],
  ['<h3>Extra hands for the weeks that matter.</h3>', '<h3>أيدٍ إضافية في الأسابيع المهمة.</h3>'],
  ['<p>Ramadan, White Friday and back-to-school. Agents trained on your products before the rush starts, then scaled back when it ends.</p>',
   '<p>رمضان والجمعة البيضاء والعودة إلى المدارس. فريق مدرَّب على منتجاتكم قبل بدء الضغط، ثم نعود للحجم المعتاد بعد انتهائه.</p>'],
  ['<span class="tag">Ramadan</span><span class="tag">White Friday</span><span class="tag">Back-to-school</span>',
   '<span class="tag">رمضان</span><span class="tag">الجمعة البيضاء</span><span class="tag">العودة إلى المدارس</span>'],
  ['More on peak-season cover <svg', 'المزيد عن تغطية المواسم <svg'],
  ['<li>Training finished before peak week</li>', '<li>التدريب ينتهي قبل أسبوع الذروة</li>'],
  ['<li>Evening and night cover as your hours stretch</li>', '<li>تغطية المساء والليل مع امتداد ساعات عملكم</li>'],
  ['<li>Same quality scorecard as your core team</li>', '<li>بطاقة الجودة نفسها التي يُقيَّم بها فريقكم الأساسي</li>'],
  ['<li>Same account manager all year</li>', '<li>مدير الحساب نفسه طوال العام</li>'],

  // trained
  ['Trained on your business <em>before they touch a customer.</em>', 'مدرَّبون على عملكم <em>قبل أن يتحدثوا مع أي عميل.</em>'],
  ['Every agent goes through a week of training built from your own materials, then has to pass your scorecard before going live. After that, their conversations keep getting reviewed.',
   'يمر كل موظف بأسبوع تدريب مبني على موادكم أنتم، ثم عليه أن يجتاز بطاقة التقييم لديكم قبل أن يبدأ العمل. وبعد ذلك تستمر مراجعة محادثاته.'],
  ['<span class="d">Day 1</span><h3>Your business</h3><p>Products, customers, policies, delivery times, refunds and warranties.</p>',
   '<span class="d">اليوم 1</span><h3>عملكم</h3><p>المنتجات والعملاء والسياسات ومواعيد التوصيل والاسترجاع والضمانات.</p>'],
  ['<span class="d">Day 2</span><h3>Your tools</h3><p>Your helpdesk, order lookup, tagging and saved replies.</p>',
   '<span class="d">اليوم 2</span><h3>أدواتكم</h3><p>نظام الدعم والبحث عن الطلبات والتصنيف والردود الجاهزة.</p>'],
  ['<span class="d">Day 3</span><h3>Your voice</h3><p>Tone of voice, the reply library, and writing standards in Arabic and English.</p>',
   '<span class="d">اليوم 3</span><h3>أسلوبكم</h3><p>نبرة الخطاب ومكتبة الردود ومعايير الكتابة بالعربية والإنجليزية.</p>'],
  ['<span class="d">Day 4</span><h3>The hard cases</h3><p>Escalation rules, edge cases, data protection and security.</p>',
   '<span class="d">اليوم 4</span><h3>الحالات الصعبة</h3><p>قواعد التصعيد والحالات الاستثنائية وحماية البيانات والأمن.</p>'],
  ['<span class="d">Days 5–6</span><h3>Practice</h3><p>Mock conversations built from your real past tickets, scored on your scorecard.</p>',
   '<span class="d">اليومان 5–6</span><h3>التطبيق</h3><p>محادثات تجريبية مبنية على تذاكركم السابقة، تُقيَّم ببطاقة التقييم لديكم.</p>'],
  ['<span class="d">Day 7</span><h3>Certification</h3><p>20 scored mock conversations. An agent who doesn\'t pass repeats practice and doesn\'t go live.</p>',
   '<span class="d">اليوم 7</span><h3>الاعتماد</h3><p>20 محادثة تجريبية مقيَّمة. من لا يجتازها يعيد التطبيق ولا يبدأ العمل.</p>'],
  ['<span class="kicker">Quality checks</span>', '<span class="kicker">فحوص الجودة</span>'],
  ['<h3>Every review is scored on your scorecard.</h3>', '<h3>كل مراجعة تُقيَّم ببطاقة التقييم لديكم.</h3>'],
  ['<p>Pick a check to see what it looks at in a real conversation.</p>', '<p>اختاروا فحصًا لتروا ما الذي يراجعه في محادثة حقيقية.</p>'],
  ['aria-label="Quality checks" id="crit"', 'aria-label="فحوص الجودة" id="crit"'],
  ['data-c="acc">Accuracy</button>', 'data-c="acc">الدقة</button>'],
  ['data-c="tone">Tone</button>', 'data-c="tone">الأسلوب</button>'],
  ['data-c="pol">Policy</button>', 'data-c="pol">السياسات</button>'],
  ['data-c="res">Resolution</button>', 'data-c="res">الحل</button>'],
  ['data-c="lang">Language</button>', 'data-c="lang">اللغة</button>'],
  ['data-c="proc">Process</button>', 'data-c="proc">الإجراءات</button>'],
  ['aria-live="polite">Is every fact right? Order status, delivery date and refund amount match what your systems say.</p>',
   'aria-live="polite">هل كل معلومة صحيحة؟ حالة الطلب وموعد التوصيل ومبلغ الاسترجاع تطابق ما في أنظمتكم.</p>'],
  ['<li><b>Soft launch</b><span>Every conversation reviewed and corrected before habits form</span></li>', '<li><b>الإطلاق التجريبي</b><span>تُراجع كل محادثة وتُصحَّح قبل أن تترسخ العادات</span></li>'],
  ['<li><b>Every week</b><span>A sample of each agent\'s conversations scored, with coaching on every miss</span></li>', '<li><b>كل أسبوع</b><span>تُقيَّم عينة من محادثات كل موظف، مع توجيه على كل خطأ</span></li>'],
  ['<li><b>With you</b><span>Scores calibrated with your team so we grade the way you would</span></li>', '<li><b>معكم</b><span>نوحّد التقييم مع فريقكم لنقيّم كما تقيّمون أنتم</span></li>'],
  ['aria-label="Sample conversation being reviewed"', 'aria-label="محادثة نموذجية قيد المراجعة"'],
  ['<span>Review · WhatsApp</span><span class="score" id="qc-score">Scorecard</span>', '<span>مراجعة · واتساب</span><span class="score" id="qc-score">بطاقة التقييم</span>'],
  ['<div class="qb c" data-c="">Hi, I ordered a kettle on Sunday and it arrived broken. Order 48213.</div>', '<div class="qb c" data-c="">مرحبًا، طلبت غلاية يوم الأحد ووصلت مكسورة. رقم الطلب 48213.</div>'],
  ['<div class="qb a" data-c="tone lang">I\'m sorry it arrived like that, that\'s not the experience we want for you.</div>', '<div class="qb a" data-c="tone lang">نأسف لوصولها بهذا الشكل، هذه ليست التجربة التي نريدها لكم.</div>'],
  ['<div class="qb a" data-c="proc pol">I\'ve checked order 48213 against the name on your account.</div>', '<div class="qb a" data-c="proc pol">تحققت من الطلب 48213 ومطابقته للاسم في حسابكم.</div>'],
  ['<div class="qb a" data-c="acc pol">It\'s within the 14-day return window, so I can send a replacement or refund it in full.</div>', '<div class="qb a" data-c="acc pol">الطلب ضمن مهلة الإرجاع البالغة 14 يومًا، لذا يمكنني إرسال بديل أو استرجاع المبلغ كاملًا.</div>'],
  ['<div class="qb c" data-c="">A replacement please.</div>', '<div class="qb c" data-c="">بديل من فضلكم.</div>'],
  ['<div class="qb a" data-c="acc res">Done. Your replacement leaves today and arrives Thursday. The courier will collect the broken one.</div>', '<div class="qb a" data-c="acc res">تم. يخرج البديل اليوم ويصل يوم الخميس، وسيستلم المندوب الغلاية المكسورة.</div>'],
  ['<div class="qb a" data-c="proc res">Tagged: damaged item · replacement · resolved</div>', '<div class="qb a" data-c="proc res">التصنيف: منتج تالف · بديل · تم الحل</div>'],

  // standard
  ['Your customers <em>stop waiting.</em>', 'عملاؤكم <em>لن ينتظروا بعد اليوم.</em>'],
  ['Compare a typical support desk with the service levels we commit to in every contract.', 'قارنوا بين مكتب دعم معتاد ومستويات الخدمة التي نلتزم بها في كل عقد.'],
  ['<div class="seg" role="group" aria-label="Compare"><span class="knob" aria-hidden="true"></span><button type="button" aria-pressed="false">Typical desk</button><button type="button" aria-pressed="true">With Zameel</button></div>',
   '<div class="seg" role="group" aria-label="قارنوا"><span class="knob" aria-hidden="true"></span><button type="button" aria-pressed="false">المكتب المعتاد</button><button type="button" aria-pressed="true">مع زميل</button></div>'],
  ['aria-label="Slide from a typical desk to Zameel"', 'aria-label="اسحبوا من المكتب المعتاد إلى زميل"'],
  ['<span class="lbl">Time to first reply on a customer email</span>', '<span class="lbl">وقت أول رد على بريد العميل</span>'],
  ['<span class="lbl">Customer emails that get a reply at all</span>', '<span class="lbl">رسائل البريد التي تحصل على رد أصلًا</span>'],
  ['<span class="lbl">Evening messages answered the same day</span>', '<span class="lbl">رسائل المساء التي يُرد عليها في اليوم نفسه</span>'],
  ['<span class="val" data-m="0">1h</span>', '<span class="val" data-m="0">ساعة</span>'],
  ['<div><b>&lt; 2 min</b><span>First reply on WhatsApp and live chat</span></div>', '<div><b>أقل من دقيقتين</b><span>أول رد على واتساب والمحادثة المباشرة</span></div>'],
  ['<div><b>1 hour</b><span>First reply on email, in covered hours</span></div>', '<div><b>ساعة واحدة</b><span>أول رد على البريد، ضمن ساعات التغطية</span></div>'],
  ['<div><b>100%</b><span>Arabic answered by a native speaker</span></div>', '<div><b>100%</b><span>رسائل عربية يرد عليها متحدث أصلي</span></div>'],
  ['<div><b>Weekly</b><span>Performance report on your account</span></div>', '<div><b>أسبوعي</b><span>تقرير أداء عن حسابكم</span></div>'],
  ['Typical desk: email figures from SuperOffice\'s study of 1,000 companies (2018); the evening figure is for a desk that closes at 5pm. With Zameel: the service levels above.',
   'المكتب المعتاد: أرقام البريد من دراسة SuperOffice على 1,000 شركة (2018)، ورقم المساء لمكتب يغلق الساعة 5 مساءً. مع زميل: مستويات الخدمة أعلاه.'],

  // dashboard section
  ['Your account, <em>open any time.</em>', 'حسابكم، <em>مفتوح في أي وقت.</em>'],
  ['Volumes, reply times and quality scores on one screen, so you never wait for a month-end PDF to know how your customers are being treated.',
   'الأحجام وأوقات الرد ودرجات الجودة على شاشة واحدة، فلا تنتظرون تقرير نهاية الشهر لتعرفوا كيف يُعامَل عملاؤكم.'],
  ['Zameel <span>· Your brand</span>', 'زميل <span>· علامتكم</span>'],
  ['<span class="sample">Example account</span>', '<span class="sample">حساب تجريبي</span>'],
  ['<div class="dseg" role="group" aria-label="Period"><button type="button" aria-pressed="true" data-p="w">This week</button><button type="button" aria-pressed="false" data-p="m">Last 4 weeks</button></div>',
   '<div class="dseg" role="group" aria-label="الفترة"><button type="button" aria-pressed="true" data-p="w">هذا الأسبوع</button><button type="button" aria-pressed="false" data-p="m">آخر 4 أسابيع</button></div>'],
  ['<span>Conversations</span><b data-k="0">', '<span>المحادثات</span><b data-k="0">'],
  ['<span>Median first reply</span><b data-k="1">', '<span>وسيط أول رد</span><b data-k="1">'],
  ['<span>Resolved first contact</span><b data-k="2">', '<span>حُلّت من أول تواصل</span><b data-k="2">'],
  ['<span>Quality score</span><b data-k="3">', '<span>درجة الجودة</span><b data-k="3">'],
  ['<b data-k="1">1m 42s</b><i data-d="1">Target under 2 min</i>', '<b data-k="1">1 د 42 ث</b><i data-d="1">الهدف أقل من دقيقتين</i>'],
  ['<i data-d="0">▲ 6% vs last period</i>', '<i data-d="0">▲ 6% مقارنة بالأسبوع الماضي</i>'],
  ['<i data-d="2">▲ 2 pts</i>', '<i data-d="2">▲ نقطتان</i>'],
  ['<i data-d="3">Your scorecard</i>', '<i data-d="3">بطاقة التقييم لديكم</i>'],
  ['<figcaption>Conversations per day <span>Each dot is 10 conversations</span></figcaption>', '<figcaption>المحادثات يوميًا <span>كل نقطة = 10 محادثات</span></figcaption>'],
  ['aria-label="Dot chart of conversations per day, example data"', 'aria-label="مخطط نقطي للمحادثات اليومية، بيانات تجريبية"'],
  ['<figcaption>Quality by check</figcaption>', '<figcaption>الجودة حسب الفحص</figcaption>'],
  ['aria-label="Dot bars of quality score by check, example data"', 'aria-label="أعمدة نقطية لدرجة الجودة حسب الفحص، بيانات تجريبية"'],
  ['<figcaption>When customers write <span>Bigger dot, more conversations</span></figcaption>', '<figcaption>متى يكتب العملاء <span>كلما كبرت النقطة زادت المحادثات</span></figcaption>'],
  ['aria-label="Dot heat map of conversations by day and hour, example data"', 'aria-label="خريطة نقطية للمحادثات حسب اليوم والساعة، بيانات تجريبية"'],
  ['>Open the full dashboard <svg', '>افتحوا لوحة المتابعة كاملة <svg'],
  ['<span>Conversations, quality, team and reports, on an example account.</span>', '<span>المحادثات والجودة والفريق والتقارير، على حساب تجريبي.</span>'],

  // one seat
  ['The salary is the part <em>you can see.</em>', 'الراتب هو الجزء <em>الذي ترونه فقط.</em>'],
  ['Every in-house hire brings costs that never show on the payslip. With Zameel, all of them sit inside one monthly seat.',
   'كل موظف داخلي يأتي بتكاليف لا تظهر في كشف الراتب. مع زميل، كلها داخل مقعد شهري واحد.'],
  ['<div class="seat-seg" role="group" aria-label="Compare"><span class="knob" aria-hidden="true"></span><button type="button" aria-pressed="true" data-m="0">Hiring in-house</button><button type="button" aria-pressed="false" data-m="1">A Zameel seat</button></div>',
   '<div class="seat-seg" role="group" aria-label="قارنوا"><span class="knob" aria-hidden="true"></span><button type="button" aria-pressed="true" data-m="0">التوظيف الداخلي</button><button type="button" aria-pressed="false" data-m="1">مقعد مع زميل</button></div>'],
  ['aria-label="Dot illustration: the salary sits above the waterline and the other costs of hiring sit below it. With a Zameel seat they gather into one block."',
   'aria-label="رسم نقطي: الراتب فوق سطح الماء وبقية تكاليف التوظيف تحته. مع مقعد زميل تجتمع كلها في كتلة واحدة."'],
  ['<b>Salary</b><span>The number on the offer letter.</span>', '<b>الراتب</b><span>الرقم المكتوب في عرض العمل.</span>'],
  ['<b>Benefits, visas and insurance</b><span>Added on top of every salary.</span>', '<b>المزايا والتأشيرات والتأمين</b><span>تُضاف فوق كل راتب.</span>'],
  ['<b>Recruiting</b><span>Job ads, interviews and notice periods before anyone starts.</span>', '<b>التوظيف</b><span>إعلانات الوظائف والمقابلات وفترات الإشعار قبل أن يبدأ أحد.</span>'],
  ['<b>Training</b><span>The weeks before a new hire can work alone.</span>', '<b>التدريب</b><span>الأسابيع التي تسبق قدرة الموظف الجديد على العمل وحده.</span>'],
  ['<b>Replacing people who leave</b><span>Recruiting and training, all over again.</span>', '<b>تعويض من يغادرون</b><span>التوظيف والتدريب من جديد.</span>'],
  ['<b>Supervision and quality checks</b><span>Someone to schedule, review and coach the team.</span>', '<b>الإشراف وفحص الجودة</b><span>من يجدول ويراجع ويوجّه الفريق.</span>'],
  ['<b>Laptops, licences and desks</b><span>Equipment, software seats and space for every agent.</span>', '<b>الأجهزة والتراخيص والمكاتب</b><span>المعدات وتراخيص البرامج والمساحة لكل موظف.</span>'],
  ['<b>Cover for leave and peaks</b><span>Sick days, holidays, evenings and the busy season.</span>', '<b>تغطية الإجازات والذروة</b><span>الإجازات المرضية والعطلات والمساء ومواسم الضغط.</span>'],
  ['<em class="you">You pay</em><em class="inc">In the seat</em>', '<em class="you">تدفعونه</em><em class="inc">داخل المقعد</em>'],
  ['<p>One monthly price per seat, confirmed after a 30-minute call.</p>', '<p>سعر شهري واحد لكل مقعد، يُحدَّد بعد مكالمة مدتها 30 دقيقة.</p>'],
  ['>Get your quote <svg', '>اطلبوا عرض السعر <svg'],

  // record
  ['Our leadership has turned a support team around <em>before.</em>', 'سبق لفريق قيادتنا أن <em>قلب أداء فريق دعم.</em>'],
  ['Our leadership has taken over existing customer support teams and rebuilt how they work. These are the medians from those teams\' quality scorecards, before and after.',
   'تولى فريق قيادتنا إدارة فرق دعم قائمة وأعاد بناء طريقة عملها. هذه هي القيم الوسيطة من بطاقات تقييم الجودة لتلك الفرق، قبل وبعد.'],
  ['Source: internal QA scorecards from support teams run by our leadership.', 'المصدر: بطاقات تقييم جودة داخلية من فرق دعم أدارها فريق قيادتنا.'],
  ['<span>Refused calls</span>', '<span>المكالمات المرفوضة</span>'],
  ['<span>Ticket handling time</span><b>104<i>→</i>17 min</b>', '<span>وقت معالجة التذكرة</span><b><bdi>104</bdi><i>←</i><bdi>17 دقيقة</bdi></b>'],
  ['<span>Untracked time per agent</span><b>48<i>→</i>12 min</b>', '<span>الوقت غير المسجل لكل موظف</span><b><bdi>48</bdi><i>←</i><bdi>12 دقيقة</bdi></b>'],
  ['<b>6.3%<i>→</i>0.5%</b>', '<b><bdi>6.3%</bdi><i>←</i><bdi>0.5%</bdi></b>'],
  ['<span>Quality score (IQS)</span><b>80%<i>→</i>95%</b>', '<span>مؤشر الجودة (IQS)</span><b><bdi>80%</bdi><i>←</i><bdi>95%</bdi></b>'],
  ['<div class="legend"><span>Before</span><span class="af">After</span></div>', '<div class="legend"><span>قبل</span><span class="af">بعد</span></div>'],

  // how we start
  ['From first call to a <em>running desk.</em>', 'من أول مكالمة إلى <em>مكتب يعمل.</em>'],
  ['<span class="when">Week 0</span><h3>Talk</h3><p>A 30-minute call about your channels, volumes and tone of voice.</p>', '<span class="when">الأسبوع 0</span><h3>نتحدث</h3><p>مكالمة مدتها 30 دقيقة عن قنواتكم وحجم الرسائل وأسلوبكم.</p>'],
  ['<span class="when">Weeks 1 to 8</span><h3>Pilot</h3><p>We run one channel inside your tools and send you the numbers every week.</p>', '<span class="when">من الأسبوع 1 إلى 8</span><h3>نجرّب</h3><p>نشغّل قناة واحدة داخل أدواتكم ونرسل لكم الأرقام كل أسبوع.</p>'],
  ['<span class="when">After the pilot</span><h3>Grow</h3><p>Add channels, hours or agents once the results work for you.</p>', '<span class="when">بعد التجربة</span><h3>نكبر</h3><p>أضيفوا قنوات أو ساعات أو موظفين عندما تقتنعون بالنتائج.</p>'],

  // together
  ['<span class="w pop" style="transition-delay:.1s">You</span> <span class="w" style="transition-delay:.5s"><em>grow.</em></span>',
   '<span class="w pop" style="transition-delay:.1s">أنتم</span> <span class="w" style="transition-delay:.5s"><em>تكبرون.</em></span>'],
  ['<span class="w g" style="transition-delay:1s">We</span> <span class="w o" style="transition-delay:1.5s"><em>support.</em></span>',
   '<span class="w g" style="transition-delay:1s">ونحن</span> <span class="w o" style="transition-delay:1.5s"><em>ندعم.</em></span>'],
  ['You grow the business. We look after your customers, in Arabic and English, to one standard.', 'أنتم تكبّرون أعمالكم، ونحن نهتم بعملائكم، بالعربية والإنجليزية، وبمعيار واحد.'],

  // faq
  ['What teams ask us <em>first.</em>', 'أول ما <em>تسألنا عنه الفرق.</em>'],
  ['Which hours do you cover?<span', 'ما ساعات العمل التي تغطونها؟<span'],
  ['<p>Yours. We staff your business hours in your time zone, including evenings, weekends and peak seasons, with Arabic and English on every shift.</p>',
   '<p>ساعات عملكم أنتم. نغطي دوامكم بتوقيتكم، بما في ذلك المساء وعطلات نهاية الأسبوع والمواسم، بالعربية والإنجليزية في كل وردية.</p>'],
  ['Do you work in our tools or yours?<span', 'هل تعملون على أدواتنا أم أدواتكم؟<span'],
  ['<p>Yours. We log in to your helpdesk, CRM or back-office system with accounts you control, so your data and history stay with you.</p>',
   '<p>على أدواتكم. ندخل إلى نظام الدعم أو إدارة العملاء أو النظام المكتبي لديكم بحسابات تتحكمون بها، فتبقى بياناتكم وسجلّكم عندكم.</p>'],
  ['Which languages do your agents work in?<span', 'بأي لغات يعمل فريقكم؟<span'],
  ['<p>Arabic and English. Our agents are native Arabic speakers with fluent English, and they reply in a natural, friendly register. Nothing is machine translated.</p>',
   '<p>العربية والإنجليزية. فريقنا من المتحدثين الأصليين بالعربية يجيدون الإنجليزية، ويردون بأسلوب طبيعي وودود. لا شيء مترجم آليًا.</p>'],
  ['What is the smallest team we can start with?<span', 'ما أصغر فريق يمكن أن نبدأ به؟<span'],
  ['<p>Three seats for three months. You can start with a pilot on one channel and add seats once the weekly numbers work for you.</p>',
   '<p>ثلاثة مقاعد لمدة ثلاثة أشهر. يمكنكم البدء بتجربة على قناة واحدة، ثم إضافة مقاعد عندما تناسبكم الأرقام الأسبوعية.</p>'],
  ['Who is our point of contact?<span', 'من هو جهة التواصل لدينا؟<span'],
  ['<p>A dedicated account manager, from the first call onward. Senior managers stay directly involved in your account and join your weekly review.</p>',
   '<p>مدير حساب مخصص، من أول مكالمة. ويبقى كبار المدراء مشاركين مباشرة في حسابكم ويحضرون مراجعتكم الأسبوعية.</p>'],

  // contact
  ['<p class="tag-line">Your operations. Our people. One standard.</p>', '<p class="tag-line">عملياتكم. فريقنا. معيار واحد.</p>'],
  ['<p>Or email <span class="mail">info@zameel.cx</span></p>', '<p>أو راسلونا على <span class="mail" dir="ltr">info@zameel.cx</span></p>'],
  ['<p class="svc">Messaging · Email · Voice · Back-office &amp; KYC · Arabic and English</p>', '<p class="svc">المحادثات · البريد · المكالمات · الأعمال المكتبية والتحقق · بالعربية والإنجليزية</p>'],
  ['<h2 id="ct-h">Tell us where your support hurts.</h2>', '<h2 id="ct-h">أخبرونا أين تتعب خدمة عملائكم.</h2>'],
  ['<p>Share a few details. A senior manager replies within one working day to set up a 30-minute call.</p>', '<p>شاركونا بعض التفاصيل، ويرد عليكم أحد كبار المدراء خلال يوم عمل واحد لترتيب مكالمة مدتها 30 دقيقة.</p>'],
  ['<label for="f-name">Your name</label>', '<label for="f-name">الاسم</label>'],
  ['<label for="f-company">Company</label>', '<label for="f-company">الشركة</label>'],
  ['<label for="f-email">Work email</label>', '<label for="f-email">البريد الإلكتروني للعمل</label>'],
  ['placeholder="name@company.com" required>', 'placeholder="name@company.com" dir="ltr" required>'],
  ['<label for="f-wa">WhatsApp number</label>', '<label for="f-wa">رقم واتساب</label>'],
  ['autocomplete="tel">', 'autocomplete="tel" dir="ltr">'],
  ['<label for="f-need">What do you need help with?</label>', '<label for="f-need">بماذا تحتاجون المساعدة؟</label>'],
  ['<option>Customer support</option><option>Back-office and underwriting</option><option>Peak-season cover</option><option>Not sure yet</option>',
   '<option value="Customer support">خدمة العملاء</option><option value="Back-office and underwriting">الأعمال المكتبية والاكتتاب</option><option value="Peak-season cover">تغطية المواسم</option><option value="Not sure yet">لم نقرر بعد</option>'],
  ['<label for="f-website">Website</label>', '<label for="f-website">الموقع</label>'],
  ['>Request my call <svg', '>اطلبوا مكالمتكم <svg'],
  ['<small>We reply within one working day.</small>', '<small>نرد خلال يوم عمل واحد.</small>'],
  // film
  ['Watch the film <small>0:22</small>', 'شاهدوا الفيلم <small>0:22</small>'],
  ['Zameel in <em>22 seconds.</em>', 'زميل في <em>22 ثانية.</em>'],
  ['How a team that works your hours, in your tools and in both languages fits into your day.', 'كيف يندمج في يومكم فريق يعمل في ساعاتكم، داخل أدواتكم، وباللغتين.'],
  ['aria-label="22 second film about how Zameel works"', 'aria-label="فيلم من 22 ثانية عن طريقة عمل زميل"'],
  ['>Your customers don’t keep office hours.<', '>عملاؤكم لا يلتزمون بساعات الدوام.<'],
  ['>Shifts planned around when your customers write and call.<', '>ورديات مخططة حسب الأوقات التي يتواصل فيها عملاؤكم.<'],
  ['>WhatsApp, email and calls, in one thread with one team.<', '>واتساب وبريد ومكالمات، في محادثة واحدة مع فريق واحد.<'],
  ['>Trained on your product, your tools and your tone.<', '>مدرَّبون على منتجكم وأدواتكم وأسلوبكم.<'],
  ['>A weekly report from one named account manager.<', '>تقرير أسبوعي من مدير حساب واحد تعرفونه بالاسم.<'],
  ['aria-label="Zameel film"', 'aria-label="فيلم زميل"'],
  ['<button class="lb-x" type="button" aria-label="Close">', '<button class="lb-x" type="button" aria-label="إغلاق">'],
];
